### ISSUE TITLE
Hello, the LdfSignalInitValue enum  type cannot be parsed,

### ISSUE THREAD

**Issue by z104655** [zpg6/lin-ldf#2]
<img width="739" alt="截屏2024-11-10 10 14 50" src="https://github.com/user-attachments/assets/ae4dd4b0-2be0-4067-98c2-a47bf04782f6">

**Comment by zpg6** [comment]
Hello @z104655 - I made this value available and published a new release `0.0.20`. Let me know if I can help further :)
